services:
  fastapi-service:
    build: .
    container_name: fastapi-baseline
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis-cache
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge